name: Hello World hru? Training Workflow

on:
  workflow_dispatch:

jobs:
    greet:
        env:
            MY_ENV: "John Doe"
            runs-on: ubuntu-latest
            steps:
            - name: Greet the User hello
        run: echo "Hello World! hru?"
         - run: ls -l
         - uses: actions/checkout@v2
         - run: ls -l
         - name: Run a multi-line script
          run: |
             echo "Hello $MY_ENV"
           echo "Hello $GITHUB_ACTOR"
        
